# ======================
# Charybdis BLE-only Split
# ======================

CONFIG_ZMK_KEYBOARD_NAME="Charybdis"

#
# Split keyboard
#
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y   # левая половина
CONFIG_ZMK_SPLIT_USB=n            # USB отключен, т.к. нет кабеля

#
# Bluetooth
#
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

#
# HID over BLE
#
CONFIG_ZMK_BLE_HID=y
